---
- name: Debug update_secrets
  hosts: vm-10-1-230-59.ans.cee.ral3.lab.eng.rdu2.redhat.com
  connection: local
  gather_facts: false
  tasks:
    - name: "test"
      ansible.platform.user:
        username: "test"
        first_name: "test"
        last_name: "test"
        password: "test1234567"
        update_secrets: true
