---
- name: Debug update_secrets
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: "test"
      ansible.platform.user:
        username: "test"
        first_name: "test"
        last_name: "test"
        password: "test1234567"
        update_secrets: true
